### ISSUE TITLE
xaringan series

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/garrickadenbuie-com#44]
- [ ] xaringan -> powerpoint
- [ ] xaringan slides from templates
- [ ] xaringan auto-advance/rotating slides
- [ ] hosting xaringan slides on github/netlify

**Comment by gadenbuie** [comment]
logos on all slides

```html
<!-- insert-logo.html -->
<style>
.logo {
	background-image: url(figures/moffittlogo.png);
	background-size: contain;
	background-repeat: no-repeat;
	position: absolute;
	bottom: 0%;
	left: 2%;
	width: 152px;
	height: 53px;
	z-index: 0;
}
</style>

<script>
document.querySelectorAll('.remark-slide-content:not(.hide-logo)').forEach(el => {
  el.innerHTML += '<div class="logo"></div>';
});
</script>
```

```yaml
output:
  xaringan::moon_reader:
    includes:
      after_body: insert-logo.html
```
