### ISSUE TITLE
tweak sidebar links

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/garrickadenbuie-com#45]
```css
.contact-list li {
  display: inline-block;
  width: 25px;
}

.contact-list {
  display: flex;
  flex-direction: row;
  width: 100%;
  justify-content: space-between;
}
```
