### ISSUE TITLE
Fix width of main panel on medium screen widths

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/garrickadenbuie-com#68]
```css
.content {
	margin-left: 17rem; /* fix this */
	margin-right: 4rem;
}
```
